# -*- coding: utf-8 -*-
"""Copia de Clase_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15jdsaXA8YoUVxyYdYb2BP3yA-IPSun6t

La idea es que ustedes vayan resolviendo los ejercicios sin la necesidad de instalarse nada en sus computadoras. 
Antes que nada, creen una copia de este archivo en su ***Google Drive*** para tener permisos de edición, luego pueden compartirlo con quien quieran, tengan cuidado con los permisos al momento de compartir!!!!!!!. Si quieren, nos pueden compartir su documento a los docentes para que hagamos las correcciones y ayudemos con las dudas.

### Agustin: **agustin.otero@estudiantes.unahur.edu.ar** ###


En los bloques de código como el que les aparece aca abajo, se puede programar en Python, al pararse dentro del bloque, aparecerá un ícono de "*play*" en la esquina superior izquierda, "*clickeando*" en este ícono, se ejecuta el código escrito y se muestra la salida debajo, probemos:

Para "crear" una funcion debemos utilizar la palabra reservada **def** continuado de el nombre (en camelCase) y terminado por dos puntos **(:)**

Para **invocarla** bastara con "nombrarla" con los parentesis correspondientes, y se ejecutara el codigo que encierra.
"""

def saludador():
  #Proposito: Saluda al usuario
  print("hola")

saludador()

saludador()

"""Las funciones no solo "hacen cosas" , sino que tambien pueden devolver valores para poder utilizarlos en otros lados."""

def pi():
  #Proposito: almacenar el valor de pi con 5 decimales  si lo nombro despues pero no ejecuto antes el nombre te va a tirar error 
  return(3.14159)

print(pi())

"""Tambien podemos añadirle **parametros** a nuestras funciones que actuaran como variables locales para nuestra funcion.
Estas variables nosotros tenemos que indicar de que tipo son para asi poder operar con ellas de forma "generica" y poder hacer n uestro codigo "generico" y reutilizable.
"""

def sumaYMuestra(num1, num2):
  #Proposito: sumar los valores num1 y num2 y mostrarlos en pantalla
  #Param: num1 = entero o flotante (con coma )
  #       num2 = entero o flotante ( con coma )
  suma = num1 + num2
  print(suma)

sumaYMuestra(2,3)
sumaYMuestra(7,pi())

"""A las funciones que "devuelven" tambien se les pueden asignar parametros."""

def saludoPara_(nombre):
  #Proposito: saludar al usuario con el nombre indicado
  #Param: nombre = string
  return ("hola " + nombre)

print(saludoPara_("Jorge"))
print(saludoPara_("Ezequiel"))

"""A la funcion anterior le agregamos un **parametro por defecto.**

Esto significa que si el ususario al momento de invocar nuestra funcion no le indica el valor a tomar del parametro, el mismo tomara el valor por defecto que nosostros indicaremos al momento de crear el parametro.
"""

def saludoPara_(nombre = "Usuario"):
  #Proposito: saludar al usuario con el nombre indicado.
  #Param: nombre = string . Por defecto "usuario"
    return ("hola " + nombre)

print(saludoPara_("Jorge"))
print(saludoPara_())

"""Dentro de la documentacion tenemos que poner tambien la precondicion que debe cumplir el codigo previo a ejecutarlo, o las condiciones que van a hacer que nuestro codigo se rompa."""

def dividir(num1, num2):
  #Proposito: dividir num1 por num2 y mostrarlo por pantalla
  #Param: num1 = int
  #       num2 = int
  #Precon: num2 tiene que ser distinto de 0
  division = num1/num2
  print(division)

"""Ahora con lo aprendido vamos a resolver juntos este ejercicio:"""

def pedirNumero():
  #Proposito: pedir un entero por consola, y retornarlo.
  aux = int(input("ingrese un numero ")) # no esta bien porque te devuelve un strim hay que agregarle el int)
  return(aux)

def sumador(x1, x2):
  #Proposito: Sumar los valores de x1 y x2 , y retornar la suma pero no pueden llamarse iguak tiene que indicar tambien que numero pide 
  #Param: x1 = entero
  #       x2 = entero
suma = x1+x2
  return (suma)

def restador(x , x):
  #Proposito: restar los valores de x1 y x2 , y retornar la resta
  #Param: x1 = enteros
  #       x2 = enteros
  resta = x1 - x2
  return(resta)

def sumaOResta():
  #Proposito: pedirle al usuario que indique la operacion a realizar, e ingresar
  #   los datos para realizar la operacion. Terminado esto mostrar el resultado 
  #   o una indicacion de que hubo un error.
  variable ??
  print("Ingrese 1 si quiere sumar")
  print("Ingrese 2 si quiere restar")
  variable = pedir numero ()
  if condicion1:
    ??
    sumador
    variable ??
    print(f"El resultado es {variable}")  
  elif condicion2:
    ??
    restador
    variable ??
    print(f"El resultado es {variable}")  
  else:
    print("Ingresó un valor equivocado")
  print("Termine")

"""**Ejercicio 1**

Escribir una función que calcule el área de un círculo y otra que calcule el volumen de un cilindro usando la primera función.

**Ejercicio 2**

Escribir una función que reciba una muestra de números en una lista y devuelva su promedio.

**Ejercicio 3**

Escribir la función factorial(), que reciba un número entero positivo y devuelva su factorial.

Factorial = El producto de todos los números enteros positivos desde 1 hasta el numero indicado.

Factorial(4) = 1*2*3*4 = 24

**Ejercicio 4**

Realiza una función llamada medio() que a partir de dos números, devuelva su punto medio. Cuando lo tengas comprueba el punto intermedio entre -12 y 24.


El punto medio de dos números corresponde a la suma de los dos números dividida entre 2

**Ejercicio 5**

Crear una función calcularMaxMin(list) que recibe una lista con valores numéricos y devuelve el valor máximo y el mínimo. Crea un programa que pida 10 números por teclado y muestre el máximo y el mínimo, utilizando la función anterior.

**Ejercicio 6**

Realiza una función llamada recortar(numero, minimo, maximo) que reciba tres parámetros. El primero es el número a recortar, el segundo es el límite inferior y el tercero el límite superior. La función tendrá que cumplir lo siguiente:


*   Devolver el límite inferior si el número es menor que éste
*   Devolver el límite superior si el número es mayor que éste.
*   Devolver el número sin cambios si no se supera ningún límite.

**Ejercicio 7**

Escribir una función que aplique un descuento que se le indica a un precio y otra que aplique el IVA a un precio.Si se invoca la función sin pasarle el porcentaje de IVA, deberá aplicar un 21%.

Escribir una tercera función que reciba un diccionario con los precios y porcentajes de  descuento de un carrito de compras, y una de las funciones anteriores, y utilice la función pasada para aplicar los descuentos o el IVA a los productos de la cesta y devolver el precio final de la cesta.

**Ejercicio 8**

Crear una función que calcule la temperatura media de un día a partir de la temperatura máxima y mínima. Crear un programa principal, que utilizando la función anterior, vaya pidiendo la temperatura máxima y mínima de cada día y vaya mostrando la media. El programa principal pedirá el número de días que se van a introducir.

**Ejercicio 9**

Escribir dos funciones que permitan calcular:

*   La cantidad de segundos en un tiempo dado en horas, minutos y segundos.
*   La cantidad de horas, minutos y segundos de un tiempo dado en segundos.    

Escribe un programa principal con un menú donde se pueda elegir la opción de convertir a segundos, convertir a horas,minutos y segundos o salir del programa.

**Ejercicio 10**

Crear una funcion llamada “Login”, que recibe un nombre de usuario y una contraseña y te devuelve Verdadero si el nombre de usuario es “usuario1” y la contraseña es “asdasd”. Además recibe la variable que contiene el número de intentos que se ha intentado hacer login y si no se ha podido hacer login incremente este valor.

Crear un programa principal donde se pida un nombre de usuario y una contraseña y se intente hacer login, solamente tenemos tres oportunidades para intentarlo.
"""